### ISSUE TITLE
Can't clone repo and commands not found

### ISSUE THREAD

**Issue by ConTacMight** [KazKobara/plot-openssl-speed#1]
I try cloning your repo into my wsl on my windows machine and that fails with a remote: Support for password authentication was removed on August 13, 2021. 
I follow some stackoverflow solutions in setting up my credentials and then I get remote: repo not found. 
Downloading your code and unzipping it to the WSL also doesn't work because running any shell script gives command not found.

**Comment by ConTacMight** [comment]
If anyone else runs into this issue, I had to convert plot_openssl_speed.sh and plot_openssl_speed_all.sh with dos2unix (might be the byproduct of downloading and unzipping from windows into WSL environment), and add permissions with chmod +x for both.

**Comment by KazKobara** [comment]
Thank you for trying plot-openssl-speed and for your tips.
